import { Picture } from '../models/picture.model';

export const PICTURES: Picture[] = [
    {
        id: '1',
        name: 'IMG_1590',
        link: 'assets/images/instagram/IMG_1590.jpg',
        tag: ["landscape", "Balaton", "sunset"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '2',
        name: 'IMG_5554',
        link: 'assets/images/instagram/IMG_5554.jpg',
        tag: ["human", "walking"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '3',
        name: 'IMG_6237',
        link: 'assets/images/instagram/IMG_6237.jpg',
        tag: ["coffee"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '4',
        name: 'IMG_6560',
        link: 'assets/images/instagram/IMG_6560.jpg',
        tag: ["black&white", "flatlay", "EDC"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '5',
        name: 'IMG_6640',
        link: 'assets/images/instagram/IMG_6640.jpg',
        tag: ["human", "news", "freeSZTE"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '6',
        name: 'IMG_6652',
        link: 'assets/images/instagram/IMG_6652.jpg',
        tag: ["coffee"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '7',
        name: 'IMG_6675',
        link: 'assets/images/instagram/IMG_6675.jpg',
        tag: ["black&white", "human"],
        author: "Kristóf Kóczán",
        available: true,
    },
    {
        id: '8',
        name: 'IMG_6744',
        link: 'assets/images/instagram/IMG_6744.jpg',
        tag: ["coffee"],
        author: "Kristóf Kóczán",
        available: true,
    },
];
